export enum CART_ACTIONS {
    ADD_ITEM_CART = "ADD_ITEM_CART",
    REMOVE_ITEM_CART = "REMOVE_ITEM_CART",
    UPDATE_QUANTITY_ADD = "UPDATE_QUANTITY_ADD",
    UPDATE_QUANTITY_REMOVE = "UPDATE_QUANTITY_REMOE",
    CLEAN_CART = "CLEAN_CART"
}